# -*- coding: utf-8 -*-
"""Day2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PVApcH8revpMctYIAdSAwMCkoJzMzpV_
"""

#Questions 1:
#Create an empty list. Accept 10 numbers from the user and append to it the list if it is an even number.
lst=[]
for i in range (0, 10):
  num=int(input())
  if (num%2)==0:
    lst.append(num)
print()
for x in range(len(lst)): 
    print( lst[x])

#Questions 2:
#Create a notebook on LIST COMPREHENSION. This exercise is to put you in a Self learning mode

numbers = [1, 2, 3, 4, 5]
squares = [number**2 for number in numbers]
print(squares)

#Questions 3:
#Given a number n, you have to write a program that generates a dictionary d which
#contains (i, i*i), where i is from 1 to n (both included).Then you have to just print this dictionary d

n=int(input())
d=dict()
for x in range(1,n+1):
    d[x]=x**2
print(d)

#Question 4
import math
pos = [0,0]
while True:
    s = int(input("Enter Steps:     "))
    if not s:
        break
    movement = s.split(" ")
    direction = movement[0]
    steps = int(movement[1])
    if direction=="UP":
        pos[0]+=steps
    elif direction=="DOWN":
        pos[0]-=steps
    elif direction=="LEFT":
        pos[1]-=steps
    elif direction=="RIGHT":
        pos[1]+=steps
    else:
        pass
print(round(math.sqrt(pos[1]**2+pos[0]**2)))